sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

env: GRADLE_OPTS="-Xms1g -Xmx2g"
install: true
script: ./gradlew build

notifications:
  email: false
